### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by derekantrican** [dbasoftware/freshdesksharp#1]
Is this still working? I'm having some trouble trying to create a ticket with this nuget package. It doesn't throw any errors, but no tickets are created on freshdesk. Any suggestions?

**Comment by fyndor** [comment]
I think it should work.  I am not using it production as my company decided not to pursue the project that I built it for.  Looking at their api though they are still on V2 and I am pretty sure the ticket api worked fine at the time of the last commit of this repository.  Do you have any code you can share with me, maybe I can see what is going wrong?  If you send code make sure to replace your real credentials with fake credentials so your account doesn't get hijacked.

**Comment by fyndor** [comment]
Also is your Freshdesk account setup like it is when you first got it or did you put any rules in about how tickets get routed?  Could the ticket be routed in a way that it is hidden after creation because of your rules?

**Comment by derekantrican** [comment]
My Freshdesk does not have any rules. It is set up exactly how I got it.

Here is my code:

    private void SubmitTicket()
    {
        FreshdeskCredentials credentials = new FreshdeskCredentials("API-KEY");
        FreshdeskConfig config = new FreshdeskConfig()
        {
            Domain = "bulkeditcalendarevents.freshdesk.com",
            Credentials = credentials
        };
    
        using (var client = new FreshdeskClient(config))
        {
            FreshdeskTicket ticket = new FreshdeskTicket()
            {
                Email = textBoxEmail.Text,
                Name = textBoxName.Text,
                Description = richTextBox1.Text
            };
    
            client.Tickets.CreateAsync(ticket);
        }
    }

**Comment by fyndor** [comment]
Ok first off this isn't necessarily related to your issue, but you need to understand async methods. 

`client.Tickets.CreateAsync(ticket); `

I'm going to make an assumption here that you may not understand async / await pattern, so if you do understand this and didn't realize that was an async call then skip this paragraph.  This method is an asynchronous method.  I tried to hint that like Microsoft often does by putting the word Async after it.  It's return type is Task<FreshdeskTicket<TCustomFieldObject>>.  The import part is the Task part.  It returns the type FreshdeskTicket<TCustomFieldObject>, but not immediately.  It returns a Task of FreshdeskTicket<TCustomFieldObject>.  This means that when you make the call, it will return a Task of FreshdeskTicket<TCustomFieldObject>, but this doesn't mean the request is done immediately.  In fact it almost certainly isn't.  You have to "await" this task, which will wait for the task to complete and when it does it will return the actual FreshdeskTicket<TCustomFieldObject> you would expect and you know the request has completed.  If this doesn't make sense then maybe check out the example I provided in the source code [here](https://github.com/dbasoftware/freshdesksharp/blob/master/src/DBA.FreshdeskSharp/DBA.FreshdeskSharp.Examples/Program.cs).  Notice the GetAllContactsAsync method has the word async in it's signature and in the body of that method each of the 4 calls to the client api have await in front of them.  The result of all of these is the actual response from the client rather than the task of the response, which is what you want.  The main method in that same file shows a "hack" you can do to force an async method to run synchronously like you are trying to do in your example.  Notice the `GetAllContactsAsync(freshdeskDomain, freshdeskApiKey).GetAwaiter().GetResult();` call has `GetAwaiter().GetResult()` at the end.  This lets you wait until the task has complete to go to the next line in a synchronous manner.  This is far from ideal because if this task takes a long time your gui will hang until it is finished.  But if you don't want to run it truly asynchronously then this should be added to the end of your CreateAsync call.  Microsoft has some [guidance](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/) on asynchronous programming and there are many other resources on the internet to help you much better with this than I can.

Ok back to your code.  Ok for my test since I am in a console app testing this I rewrote your function as shown below and you will notice I modified your call to CreateAsync in the way I described above (i.e. the "hack")

        private static void CreateTicket()
        {
            var email = "myfakeemail@fakedomain.com";
            var name = "Fake Name";
            var description = "Some description";
            var credentials = new FreshdeskCredentials("PUT_YOUR_API_KEY_HERE");
            var config = new FreshdeskConfig
            {
                Domain = "PUT_YOUR_DOMAIN_HERE.freshdesk.com",
                Credentials = credentials
            };

            using (var client = new FreshdeskClient(config))
            {
                var ticket = new FreshdeskTicket
                {
                    Email = email,
                    Name = name,
                    Description = description
                };

                client.Tickets.CreateAsync(ticket).GetAwaiter().GetResult();
            }
        }


This is basically your code with the domain replaced, the api key replaced, your text boxes replaced with variables because I am in a console app, and the `.GetAwaiter().GetResult();` part added to the end of the CreateAsync call so you can call it synchronously.  If you try and do this you will now get an error.  Your version of the call did cause an error, but it was "swallowed" up by the task because you never awaited it or used this "hack".  But now that we are waiting for the task to finish you see the error.

![image](https://user-images.githubusercontent.com/766594/50198404-2022f500-0311-11e9-86e5-3a10112e9304.png)

The client api will throw a custom error type that I created called FreshdeskException and notice how it has a special property on it called Errors which is a list of errors returned by the Freshdesk api server.  The image above shows the errors your code should cause.  They are trying to tell you that you must have a Subject, and that the fr_due_by and due_by fields (FrDueBy and DueBy in my client library) must be filled out with a time that is later than the ticket creation time.  FrDueBy is the time by which the first response to the ticket should be made and and DueBy is the time at which the ticket should be resolved by.  The Subject field is something you are just going to have to include to get the ticket created as far as I can tell.  The FrDueBy and DueBy fields though are my fault really.  I made them a DateTime instead of DateTime? (i.e. a nullable DateTime) so their default value is not null but rather the "zero" date when you don't provide a value and this gets interpreted by Freshdesk as a bad timestamp rather than not having a value.  I have uploaded a new version which no longer requires you to provide FrDueBy or DueBy which should show up on nuget shortly.

**Comment by fyndor** [comment]
Let me know if the above solves your issue.

**Comment by derekantrican** [comment]
Thank you! That definitely helped me! I know what asynchronous is and a little bit about how to program with it, but I didn't realize that it wouldn't throw an exception without the awaiter.

Now I've got the tickets being created in FreshDesk with this code:

    private void SubmitTicket()
    {
        FreshdeskCredentials credentials = new FreshdeskCredentials("APIKEY");
        FreshdeskConfig config = new FreshdeskConfig()
        {
            Domain = "bulkeditcalendarevents.freshdesk.com",
            Credentials = credentials
        };
    
        using (var client = new FreshdeskClient(config))
        {
            FreshdeskTicket ticket = new FreshdeskTicket()
            {
                Email = textBoxEmail.Text,
                Name = textBoxName.Text,
                Description = richTextBox1.Text,
                Subject = (radioButtonBug.Checked ? "Bug Report" : "Feature Request") + " by " + textBoxName.Text,
                Type = radioButtonBug.Checked ? "Bug Report" : "Feature Request",
                DueBy = DateTime.Today.AddDays(30),
                FrDueBy = DateTime.Today.AddDays(30)
            };
        
            client.Tickets.CreateAsync(ticket).GetAwaiter().GetResult();
        }
    }

Finally, I'm wondering how to add an attachment to the ticket with your code. I tried this (right before `Tickets.CreateAsync`) without luck:

    ticket.Attachments.Add(@"C:\Users\derek.antrican\Documents\CTL Bundling overview.docx");

**Comment by fyndor** [comment]
I see that your query now includes DueBy and FrDueBy, while you are free to include those in your creation, if you updated to the latest version of FreshdeskSharp (v0.2.1) you should no longer be required to include those and I believe the ticket would auto assign those values based on the rules you have in place in Freshdesk.

As to attachments, currently it ignores attachments on creation and update, while I believe they should be listed if you did a "Get".  This is because all attachments in their api require I special kind of processing to have them work in an API request and I have not implemented that.  If this is functionality you need I would be happy to try and get that working but it probably wouldn't happen until after the XMAS holidays.

**Comment by derekantrican** [comment]
@fyndor Thanks for all your help! You're right, the `DueBy` and `FrDueBy` are not necessary. As to attachments, I have found some C# examples of the FreshDesk API implementation here: https://github.com/freshdesk/fresh-samples/tree/master/C-Sharp and will probably write my own class

**Comment by karwalr** [comment]
Any luck with the Attachments API?

**Comment by derekantrican** [comment]
@karwalr I created this instead (adapted from a sample from the FreshDesk GitHub): https://gist.github.com/derekantrican/1ac9702c7b13317226ec0c3212906a6a

**Comment by karwalr** [comment]
> @karwalr I created this instead (adapted from a sample from the FreshDesk GitHub): https://gist.github.com/derekantrican/1ac9702c7b13317226ec0c3212906a6a

My god! Is there no nicer way to do this with the current library?

**Comment by derekantrican** [comment]
I'm not sure. All I needed was the ability to create a ticket with attachments so I didn't end up using this library
