### ISSUE TITLE
Request for Attachments

### ISSUE THREAD

**Issue by knutmarius** [dbasoftware/freshdesksharp#3]
Hi! Have you considered supporting attachments when creating tickets? Would be much appreciated

**Comment by fyndor** [comment]
Sorry for the last response.  Yes.  I haven't up to this point, because my company did not need that functionality and it is a bit more complicated than the rest of their api calls.  End of the year is kind of crazy time, but I will try and bang something out in early January if you are still interested.

**Comment by karwalr** [comment]
Still interested!

**Comment by fyndor** [comment]
Ok I will give it a shot tonight.  I am looking at the sample they provide.  It looks like it is all or nothing.  You send either the entire request over form encoded or as json and if you have attachments then it has to be form encoded.  I have never used this protocol before but I am hoping their example is enough to get me going.

**Comment by fyndor** [comment]
I am realizing I backed myself in to a bit of a corner.  While the basic FreshdeskTicket class uses a "generic" dictionary to represent custom fields, the FreshdeskTicket<TCustomFieldObject> allows you to create your own custom ticket class which utilizes a custom tailored class to hold your custom fields.  This worked fine when I was using a json library to serialize the ticket object.  When adding attachments in to the mix, I have to serialize all the fields myself which means I would need to use reflection to inspect and use custom classes used with the FreshdeskTicket object.  Not exactly something I wanted to get in to.   Ouch.  It's already a little harry with just the default dictionary for custom objects because the values are of type object which could be anything and I will have to figure out how to serialize every type you could throw at it.

**Comment by karwalr** [comment]
> I am realizing I backed myself in to a bit of a corner. While the basic FreshdeskTicket class uses a "generic" dictionary to represent custom fields, the FreshdeskTicket allows you to create your own custom ticket class which utilizes a custom tailored class to hold your custom fields. This worked fine when I was using a json library to serialize the ticket object. When adding attachments in to the mix, I have to serialize all the fields myself which means I would need to use reflection to inspect and use custom classes used with the FreshdeskTicket object. Not exactly something I wanted to get in to. Ouch. It's already a little harry with just the default dictionary for custom objects because the values are of type object which could be anything and I will have to figure out how to serialize every type you could throw at it.

Hey, thanks for checking. Agreed it is a particularly difficult API to work - I've never had to do a form encoded post for anything like this and it's turning out to be a right pain! Let us know if you do have any joy in the future with this!

**Comment by fyndor** [comment]
I'm going to try and get this working.  I am nervous though because I do believe there are a few people at least using this library and I don't want to break people's software by adding attachments.

**Comment by karwalr** [comment]
> I'm going to try and get this working. I am nervous though because I do believe there are a few people at least using this library and I don't want to break people's software by adding attachments.

Including me :). Looking at it, due to the multipart, I guess you would need a separate function for creating a ticket with an attachment rather than mixing with the current one. Their API mentions attachments for other objects too but not sure how easy it will be to make it generic.

**Comment by derekantrican** [comment]
I have a gist for creating a FreshDesk ticket with attachments here: https://gist.github.com/derekantrican/1ac9702c7b13317226ec0c3212906a6a based on their sample here: https://github.com/freshworks/fresh-samples/blob/master/C-Sharp/CreateTicketWithAttachment.cs (which is probably the sample you've been referring to)

And on the opposite end, here's some code I threw together to get a specific file from a specified ticket (in this case it happened to always be a .zip so that's hardcoded):
```csharp
private static JToken GetTicket(int ticketId)
{
    string apiPath = "/api/v2/tickets/" + ticketId;
    string responseBody = string.Empty;
    HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://" + fdDomain + ".freshdesk.com" + apiPath);
    request.ContentType = "application/json";
    request.Method = "GET";
    string authInfo = apiKey + ":X"; // It could be your username:password also.
    authInfo = Convert.ToBase64String(Encoding.Default.GetBytes(authInfo));
    request.Headers["Authorization"] = "Basic " + authInfo;
    try
    {
        Console.WriteLine("Submitting Request");
        using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
        {
            Stream dataStream = response.GetResponseStream();
            StreamReader reader = new StreamReader(dataStream);
            responseBody = reader.ReadToEnd();
            reader.Close();
            dataStream.Close();
            //return status code
            //Console.WriteLine("Status Code: {1} {0}", ((HttpWebResponse)response).StatusCode, (int)((HttpWebResponse)response).StatusCode);
        }

        return JToken.Parse(responseBody);
    }
    catch (WebException ex)
    {
        Console.WriteLine("API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id");
        Console.WriteLine("X-Request-Id: {0}", ex.Response.Headers["X-Request-Id"]);
        Console.WriteLine("Error Status Code : {1} {0}", ((HttpWebResponse)ex.Response).StatusCode, (int)((HttpWebResponse)ex.Response).StatusCode);
        using (var stream = ex.Response.GetResponseStream())
        using (var reader = new StreamReader(stream))
        {
            Console.Write("Error Response: ");
            Console.WriteLine(reader.ReadToEnd());
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine("ERROR");
        Console.WriteLine(ex.Message);
    }

    return null;
}

private static string DownloadCrashFile(JToken ticket)
{
    JToken attachments = ticket.SelectToken("attachments");
    JToken crashFileAttachment = attachments.FirstOrDefault(p => p.SelectToken("name").ToString().Contains("CRASH"));
    if (crashFileAttachment != null)
    {
        string crashFileUrl = crashFileAttachment.SelectToken("attachment_url").ToString();
        string targetFileName = Path.ChangeExtension(Path.GetTempFileName(), ".zip");

        //Console.WriteLine("Downloading file...");
        using (WebClient client = new WebClient())
        {
            client.DownloadFile(crashFileUrl, targetFileName);
        }

        //Console.WriteLine("File downloaded");
        return targetFileName;
    }

    //Console.WriteLine("No file to download");
    return null;
}
```

Hope it can help!

**Comment by fyndor** [comment]
@derekantrican Thanks for you suggestion.  I would love to add this to the library, but I don't have Freshdesk account, and this is too complex for me to comfortably make the change and assume "if it compiles it works" without actually testing it.  If anyone asks for this again I will point them to this ticket.  Maybe someone one day will use it to create a pull request that they have tested on their end and I can merge it in.
